//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tracks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub album: String,
    pub artist: String,
    pub year: i16,
    pub genre: String,
    pub url: String,
    pub image_url: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::users_tracks::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::users_tracks::Relation::Tracks.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
